config/routes.rb
EcommStore::Application.routes.draw do
  get "pages/about_us"

  get "pages/contact_us"

  get "products/index"

  get "products/show"

  get "store/index"

  get "store/show"

  root :to => 'store#index', :via => :get

  match 'products/:id' => 'store#show', :as => :store_product, :via => :get

  match 'search' => 'store#search', :as => 'search', :via => :get

  match 'search_results' => 'store#search_results', :as => 'search_results', :via => :post

  match 'light_weight' => 'store#light_weight', :as => 'light_weight', :via => :get

  match 'light_weight_results' => 'store#light_weight_results', :as => 'light_weight_results', :via => :post

  match 'forged' => 'store#forged', :as => 'forged', :via => :get

  match 'forged_results' => 'store#forged_results', :as => 'forged_results', :via => :post

  match 'off_road' => 'store#off_road', :as => 'off_road', :via => :get

  match 'off_road_results' => 'store#off_road_results', :as => 'off_road_results', :via => :post

  match 'classic' => 'store#classic', :as => 'classic', :via => :get

  match 'classic_results' => 'store#classic_results', :as => 'classic_results', :via => :post

  match 'cast' => 'store#cast', :as => 'cast', :via => :get

  match 'cast_results' => 'store#cast_results', :as => 'cast_results', :via => :post

  match 'about_us' => 'pages#about_us', :as => 'about_us', :via => :get

  match 'contact_us' => 'pages#contact_us', :as => 'contact_us', :via => :get

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  

end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body
end

app/models/category.rb
class Category < ActiveRecord::Base
  attr_accessible :name
  
  has_many :products
  
  validates :name, presence: true
  validates :name, uniqueness: true

end

app/models/customer.rb
class Customer < ActiveRecord::Base
  attr_accessible :address, :city, :email, :first_name, :last_name, :postal_code, :province_id

  belongs_to :province
  has_many :orders
  
  validates :address, :city, :email, :first_name, :last_name, :postal_code, :province_id, presence: true
  validates :province_id, numericality: true

end

app/models/line_item.rb
class LineItem < ActiveRecord::Base
  attr_accessible :order_id, :price, :product_id, :quantity

  belongs_to :product
  belongs_to :order
  
  validates :order_id, :price, :product_id, :quantity, presence: true
  validates :order_id, :product_id, uniqueness: true
  validates :order_id, :product_id, :price, :qunatity, numericality: true
  

end

app/models/order.rb
class Order < ActiveRecord::Base
  attr_accessible :customer_id, :gst_rate, :hst_rate, :pst_rate, :status
  
  has_many :line_items
  has_many :products, :through => :line_items
  belongs_to :customer
  
  validates :customer_id, :gst_rate, :hst_rate, :pst_rate, :status, presence: true
  validates :customer_id, uniqueness: true
  validates :customer_id, :product_id, :gst_rate, :hst_rate, :pst_rate, numericality: true
end

app/models/page.rb
class Page < ActiveRecord::Base
  attr_accessible :content, :name
end

app/models/product.rb
class Product < ActiveRecord::Base
  attr_accessible :bolt_pattern, :colour, :company, :description, :diameter, :name, :offset, :price, :stock_quantity, :width, :image, :category_id
  
  has_many :line_items
  has_many :orders, :through => :line_items
  belongs_to :category
  
  validates :bolt_pattern, :colour, :company, :description, :diameter, :name, :offset, :price, :stock_quantity, :width, :image, :category_id, presence: true
  validates :diameter, :offset, :price, :stock_quantity, :width, numericality: true

end

app/models/province.rb
class Province < ActiveRecord::Base
  attr_accessible :gst, :hst, :name, :pst
  has_many:customers
  
  validates :gst, :hst, :name, :pst, presence: true
  validates :hst, :gst, :pst, numericality: true
  validates :name, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def about_us
  	@about_us = Page.find(1)
  end

  def contact_us
  	@contact_us = Page.find(2)
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def index
  end

  def show
  end
end

app/controllers/store_controller.rb
class StoreController < ApplicationController
 def index
 	@products = Product.order(:name)
 end 

 def show
 	@product = Product.find(params[:id])
 end

 def search
 end

 def search_results
 	@products = Product.where("name LIKE ?", "%#{params[:keywords]}%")
 end

 def forged
 	@forged = Product.where(:category_id => 1)
 end

 def forged_results
 	@forged = Product.where("name LIKE ?", "%#{params[:keywords]}%").where(:category_id => 1)
 end

 def light_weight
 	@light_weight = Product.where(:category_id => 2)
 end

 def light_weight_results
 	@light_weight = Product.where("name LIKE ?", "%#{params[:keywords]}%").where(:category_id => 2)
 end

 def off_road
 	@off_road = Product.where(:category_id => 3)
 end

 def off_road_results
 	@off_road = Product.where("name LIKE ?", "%#{params[:keywords]}%").where(:category_id => 3)
 end

 def classic
 	@classic = Product.where(:category_id => 4)
 end

 def classic_results
 	@classic = Product.where("name LIKE ?", "%#{params[:keywords]}%").where(:category_id => 4)
 end

 def cast
 	@cast = Product.where(:category_id => 5)
 end

 def cast_results
 	@cast = Product.where("name LIKE ?", "%#{params[:keywords]}%").where(:category_id => 5)
 end

 def about_us
 	@about_us = Page.where(:id => 1)
 end

 def contact_us
 	@contact_us = Page.where(:id => 2)
 end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/store_helper.rb
module StoreHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>EcommStore</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
  
</head>
<body>


<%= yield %>

</body>
</html>

app/views/products/_product.html.erb
<section class="product">
		<h2><%=link_to product.name, store_product_path(product) %> </h2>
		<div class="description">
			<%= product.description%>
		</div>
		<p class="price">
			<%= number_to_currency product.price %>
		</p>
		<p class="diameter">
			Diameter: <%= product.diameter%>
		</p>
		<p class="width">
			Width: <%= product.width%>
		</p>
		<p class="bolt_pattern">
			Bolt Pattern: <%= product.bolt_pattern%>
		</p>
		<p>
			<strong>Category:</strong> <%= product.category.name %>
		</p>
		<p>
			<%=link_to image_tag(product.image, :width => '150'), store_product_path(product)%>
		</p>
	</section>

app/views/products/index.html.erb
<h1>Products#index</h1>
<p>Find me in app/views/products/index.html.erb</p>

app/views/products/show.html.erb
<%= render @product %>

app/views/store/about_us.html.erb
<h1>About Us</h1>
<%= @about_us.content %>

app/views/store/cast.html.erb
<h1>Cast Wheels</h1>
<p><%=link_to "Home", root_path%></p>
<%= form_tag cast_results_path do%>
	<%=text_field_tag :keywords %>
	<%= submit_tag 'Search' %>
<% end %>
<%= render @cast %>

app/views/store/cast_results.html.erb
<h2>Search Results</h2>
<% if @cast.empty? %>
<p>
	No results found for ' <%= params[:keywords] %> '
</p>
<% end %>
<%= render @cast %>

app/views/store/classic.html.erb
<h1>Classic Wheels</h1>
<p><%=link_to "Home", root_path%></p>
<%= form_tag classic_results_path do%>
	<%=text_field_tag :keywords %>
	<%= submit_tag 'Search' %>
<% end %>
<%= render @classic %>

app/views/store/classic_results.erb
<h2>Search Results</h2>
<% if @classic.empty? %>
<p>
	No results found for ' <%= params[:keywords] %> '
</p>
<% end %>
<%= render @classic %>

app/views/store/contact_us.html.erb
<h1>Contact Us</h1>
<%=@contact_us.content %>

app/views/store/forged.html.erb
<h1>Forged Aluminium Wheels</h1>
<p><%=link_to "Home", root_path%></p>
<%= form_tag forged_results_path do%>
	<%=text_field_tag :keywords %>
	<%= submit_tag 'Search' %>
<% end %>
<%= render @forged %>

app/views/store/forged_results.html.erb
<h2>Search Results</h2>
<% if @forged.empty? %>
<p>
	No results found for ' <%= params[:keywords] %> '
</p>
<% end %>
<%= render @forged %>

app/views/store/index.html.erb
<h1>Wheel Commander</h1>
<p><%=link_to "Search All", search_path%></p>
<h4>Search by Categories</h4>
<p><%=link_to "Forged Aluminum Wheels", forged_path%></p>
<p><%=link_to "Forged Aluminum Lightweight Racing Wheels", light_weight_path%></p>
<p><%=link_to "Off-Road Racing Wheels", off_road_path%></p>
<p><%=link_to "Classic Wheels", classic_path%></p>
<p><%=link_to "Cast Wheels", cast_path%></p>
<h4>Other Infomation</h4>
<p><%=link_to "About Us", about_us_path%></p>
<p><%=link_to "Contact Us", contact_us_path%></p>
<%= render @products %>

app/views/store/light_weight.html.erb
<h1>Forged Aluminium Light Weight Racing Wheels</h1>
<p><%=link_to "Home", root_path%></p>
<%= form_tag light_weight_results_path do%>
	<%=text_field_tag :keywords %>
	<%= submit_tag 'Search' %>
<% end %>
<%= render @light_weight %>

app/views/store/off_road.html.erb
<h1>Off-Road Racing Wheels</h1>
<p><%=link_to "Home", root_path%></p>
<%= form_tag off_road_results_path do%>
	<%=text_field_tag :keywords %>
	<%= submit_tag 'Search' %>
<% end %>
<%= render @off_road %>

app/views/store/off_road_results.html.erb
<h2>Search Results</h2>
<% if @off_road.empty? %>
<p>
	No results found for ' <%= params[:keywords] %> '
</p>
<% end %>
<%= render @off_road %>

app/views/store/search_results.html.erb
<h2>Search Results</h2>
<% if @products.empty? %>
<p>
	No results found for ' <%= params[:keywords] %> '
</p>
<% end %>
<%= render @products %>

app/views/store/show.html.erb
<%= render @product %>

<p>
	<%= link_to 'Home', root_path %>
</p>